schemaVersion: 1.0
name: Install-Software
description: "Downloads and installs software from Azure Storage Blob."
runner: powershell
command: ./install-software.ps1
inputs:
  - id: StorageAccountName
    type: string
    default: "stoappinstall"  # Change to your storage account name
    description: "The name of the Azure Storage Account containing software installers."
  - id: ContainerName
    type: string
    default: "advanceanalytics"  # Change to your container name
    description: "The Azure Storage Container where the software installers are stored."
